### PR TITLE
Import schema.json rather than duplicate it

### LINKED ISSUE #16: Schema.json duplicated from vega-lite
It doesn't seem to make sense to duplicate a huge automatically generated file, `schema.json` between this repository and the `vega-lite` package. It may be best to instead import this file. This would save the additional step of running `yarn schema` when upgrading dependencies, and it would also prevent the Git repository from bloating over time from changes in this file. The downside of importing this instead of duplicating it is that you would not be able to track its changes in this repository.

### PR DESCRIPTION
**Pull request by curran**
Closes #16

Related discussion in #15

### CODE REVIEW

**Comment by domoritz** [comment]
I see. That's actually a nice solution. Thanks for the PR.

**Comment by domoritz** [comment]
Please delete the package.lock since we use yarn.

**Comment by curran** [comment]
Oops! Sorry about the `package-lock`. Might as well add it to `.gitignore`. Thanks for reviewing!

**Comment by curran** [comment]
Done.

**Comment by domoritz** [comment]
Now you just need to rebase so we can merge.

**Comment by curran** [comment]
Done.

**Comment by domoritz** [comment]
I'll let @jheer squash and merge this.

**Comment by jheer** [comment]
Thanks!

**Comment by curran** [comment]
My pleasure! Thank YOU for this amazing lib.

**Pull request merged**
