### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by domoritz**
Updates dependencies and resolves potential security issue with lodash.

### CODE REVIEW

**Comment by curran** [comment]
Woohoo good to see some action here!

**Comment by curran** [comment]
It doesn't quite feel right to duplicate `api/schema.json` here. Where does that file come from? Possible to import it instead of duplicate it?

**Comment by domoritz** [comment]
It's automatically downloaded via yarn schema. I think it makes sense to have it here to track changes.

**Comment by domoritz** [comment]
Ahh, I now understand what you mean by importing the schema. This is great 👍.

**Comment by curran** [comment]
Tracking changes is a good point, but it feels like an awfully large generated file at 13,315 lines to be interested in the diffs.

Thanks!

**Pull request merged**
